# placeholder  구현 하기

### 긍정/부정 Make data (긍정: 1, 부정: 0)

---



In [0]:
sample = ['너 오늘 이뻐 보인다',
          '나는 오늘 기분이 더러워',
          '끝내주는데, 좋은 일이 있나봐',
          '나 좋은 일이 생겼어',
          '아 오늘 진짜 짜증나',
          '환상적인데, 정말 좋은거 같아']

label = [[1], [0], [1], [1], [0], [1]]

### load need modules

In [0]:
import os
import tensorflow as tf
import numpy as np

from tensorflow.keras import preprocessing

### Data Preprocessing

In [3]:
tokenizer = preprocessing.text.Tokenizer() 
tokenizer.fit_on_texts(sample) 
sequence = tokenizer.texts_to_sequences(sample) 

print("index text data : \n", sequence)
print(np.array(sequence).shape)

index text data : 
 [[4, 1, 5, 6], [7, 1, 8, 9], [10, 2, 3, 11], [12, 2, 3, 13], [14, 1, 15, 16], [17, 18, 19, 20]]
(6, 4)


In [0]:
word_index = tokenizer.word_index

print("index of each word : \n", word_index)

index of each word : 
 {'오늘': 1, '좋은': 2, '일이': 3, '너': 4, '이뻐': 5, '보인다': 6, '나는': 7, '기분이': 8, '더러워': 9, '끝내주는데': 10, '있나봐': 11, '나': 12, '생겼어': 13, '아': 14, '진짜': 15, '짜증나': 16, '환상적인데': 17, '정말': 18, '좋은거': 19, '같아': 20}


In [0]:
print("label : ", label)
print(np.array(label).shape) # np 지원 api shape

label :  [[1], [0], [1], [1], [0], [1]]
(6, 1)


### feed_dict data processing
<b> 장점 : TensorFlow 외부에서 데이터 처리를 수행하여 Python으로 쉽게 처리 할 수 있다.  
<b> 단점 : 사용자는 종종 단일 스레드에서 데이터를 처리하고 실행 속도를 저하시키는 데이터 병목 현상을 만든다.

### placeholder define

In [0]:
sequences = tf.placeholder(dtype=tf.int32, shape=[None, 4], name='sequences') # 길이가 최대 
labels = tf.placeholder(dtype=tf.int32, shape=[None,1], name='labels')

### operation define

In [5]:
print_op_sequence = tf.Print(sequences, [sequences])
print_op_labels = tf.Print(labels, [labels])

Instructions for updating:
Use tf.print instead of tf.Print. Note that tf.print returns a no-output operator that directly prints the output. Outside of defuns or eager mode, this operator will not be executed unless it is directly specified in session.run or used as a control dependency for other operators. This is only a concern in graph mode. Below is an example of how to ensure tf.print executes in graph mode:
```python
    sess = tf.Session()
    with sess.as_default():
        tensor = tf.range(10)
        print_op = tf.print(tensor)
        with tf.control_dependencies([print_op]):
          out = tf.add(tensor, tensor)
        sess.run(out)
    ```
Additionally, to use tf.print in python 2.7, users must make sure to import
the following:

  `from __future__ import print_function`



### Session run



In [6]:
with tf.Session() as sess:
  print("print sequences : ")
  print(sess.run(print_op_sequence, feed_dict={sequences: sequence}))
  print("print labels : ")
  print(sess.run(print_op_labels, feed_dict={labels: label}))

print sequences : 
[[ 4  1  5  6]
 [ 7  1  8  9]
 [10  2  3 11]
 [12  2  3 13]
 [14  1 15 16]
 [17 18 19 20]]
print labels : 
[[1]
 [0]
 [1]
 [1]
 [0]
 [1]]


### shuffle data

In [0]:
shuffle_sequence = []
shuffle_label = []
#############################################################
# random index를 만들어 낸다.
#############################################################
print(random_index)

#############################################################
# random index를 기반으로 shuffle sequence 와  
# shuffle label를 만든다. 
#############################################################
with tf.Session() as sess:
  print("Print sequences : ")
  print(sess.run(print_op_sequence, feed_dict={sequences: shuffle_sequence}))
  print("Print labels : ")
  print(sess.run(print_op_labels, feed_dict={labels: shuffle_label}))

[5 3 0 1 4 2]
Print sequences : 
[[17 18 19 20]
 [12  2  3 13]
 [ 4  1  5  6]
 [ 7  1  8  9]
 [14  1 15 16]
 [10  2  3 11]]
Print labels : 
[[1]
 [1]
 [1]
 [0]
 [0]
 [1]]


In [0]:
# ANSWER

shuffle_sequence = []
shuffle_label = []
random_index = np.random.choice(range(len(sequence)), len(sequence), replace=False)
print(random_index)

for i in random_index:
  shuffle_sequence.append(sequence[i])
  shuffle_label.append(label[i])
  
with tf.Session() as sess:
  print("Print sequences : ")
  print(sess.run(print_op_sequence, feed_dict={sequences: shuffle_sequence}))
  print("Print labels : ")
  print(sess.run(print_op_labels, feed_dict={labels: shuffle_label}))

[3 5 2 4 1 0]
Print sequences : 
[[12  2  3 13]
 [17 18 19 20]
 [10  2  3 11]
 [14  1 15 16]
 [ 7  1  8  9]
 [ 4  1  5  6]]
Print labels : 
[[1]
 [1]
 [1]
 [0]
 [0]
 [1]]


### make batch & 3 step

In [0]:
BATCH_SIZE = 2

shuffle_sequence = []
shuffle_label = []
index = 0

random_index = np.random.choice(range(len(sequence)), len(sequence), replace=False)
#############################################################
# batch size를 define되어 있는 값으로 만들어서                  
# 모든 데이터를 1epoch하도록 처리 한다.
# 위와 다른점은 배치 크기만큼 한 step씩 3번에 하도록 만든다.
#############################################################

Print sequences : 
[[12  2  3 13]
 [ 7  1  8  9]]
Print labels : 
[[1]
 [0]]
Print sequences : 
[[10  2  3 11]
 [17 18 19 20]]
Print labels : 
[[1]
 [1]]
Print sequences : 
[[14  1 15 16]
 [ 4  1  5  6]]
Print labels : 
[[0]
 [1]]


In [0]:
# ANSWER

BATCH_SIZE = 2

shuffle_sequence = []
shuffle_label = []
index = 0

random_index = np.random.choice(range(len(sequence)), len(sequence), replace=False)
  
for i in random_index:
  shuffle_sequence.append(sequence[i])
  shuffle_label.append(label[i])
  index += 1
  
  if index==BATCH_SIZE:
    with tf.Session() as sess:
      print("Print sequences : ")
      print(sess.run(print_op_sequence, feed_dict={sequences: shuffle_sequence}))
      print("Print labels : ")
      print(sess.run(print_op_labels, feed_dict={labels: shuffle_label}))
      index = 0
      shuffle_sequence.clear()
      shuffle_label.clear()  

In [0]:
import numpy as np

In [0]:
a = [1,2,3,4,5]

In [0]:
np.random.choice(range(len(a)), len(a), replace=False)

array([2, 4, 0, 1, 3])

###  2 epoch

In [0]:
EPOCH = 2
BATCH_SIZE = 2

shuffle_sequence = []
shuffle_label = []
index = 0

random_index = np.random.choice(range(len(sequence)), len(sequence), replace=False)

for j in range(EPOCH):
  for i in random_index:
    shuffle_sequence.append(sequence[i])
    shuffle_label.append(label[i])
    index += 1

    if index==BATCH_SIZE:
      with tf.Session() as sess:
        print("Print sequences : ")
        print(sess.run(print_op_sequence, feed_dict={sequences: shuffle_sequence}))
        print("Print labels : ")
        print(sess.run(print_op_labels, feed_dict={labels: shuffle_label}))
        index = 0
        shuffle_sequence.clear()
        shuffle_label.clear()  

Print sequences : 
[[10  2  3 11]
 [12  2  3 13]]
Print labels : 
[[1]
 [1]]
Print sequences : 
[[ 7  1  8  9]
 [14  1 15 16]]
Print labels : 
[[0]
 [0]]
Print sequences : 
[[17 18 19 20]
 [ 4  1  5  6]]
Print labels : 
[[1]
 [1]]
Print sequences : 
[[10  2  3 11]
 [12  2  3 13]]
Print labels : 
[[1]
 [1]]
Print sequences : 
[[ 7  1  8  9]
 [14  1 15 16]]
Print labels : 
[[0]
 [0]]
Print sequences : 
[[17 18 19 20]
 [ 4  1  5  6]]
Print labels : 
[[1]
 [1]]
