# One Hot Encoding

In [0]:
samples = ["창욱은 축구를 좋아한다",
          "중현은 축구를 싫어한다",
          "창욱은 도서관을 좋아한다",
          "중현은 도서관을 싫어한다",
          "창욱은 공부를 좋아한다",
          "중현은 공부를 싫어한다",
          "창욱은 축구를 좋아한다 중현은 축구를 싫어한다",
          "창욱은 도서관을 좋아한다 중현은 도서관을 싫어한다",
          "창욱은 공부를 좋아한다 중현은 공부를 싫어한다"]

In [0]:
token_sentences = []

for sentence in samples:
  token_sentences.append(sentence.split())

print("token_sentences : %s " %token_sentences)
word_list = " ".join(samples).split()
word_list = list(set(word_list))

print("word_list : %s" %word_list)


token_sentences : [['창욱은', '축구를', '좋아한다'], ['중현은', '축구를', '싫어한다'], ['창욱은', '도서관을', '좋아한다'], ['중현은', '도서관을', '싫어한다'], ['창욱은', '공부를', '좋아한다'], ['중현은', '공부를', '싫어한다'], ['창욱은', '축구를', '좋아한다', '중현은', '축구를', '싫어한다'], ['창욱은', '도서관을', '좋아한다', '중현은', '도서관을', '싫어한다'], ['창욱은', '공부를', '좋아한다', '중현은', '공부를', '싫어한다']] 
word_list : ['공부를', '축구를', '싫어한다', '중현은', '도서관을', '좋아한다', '창욱은']


In [0]:
char_to_int = dict((c, i) for i, c in enumerate(word_list))
char_to_int

{'공부를': 0, '도서관을': 4, '싫어한다': 2, '좋아한다': 5, '중현은': 3, '창욱은': 6, '축구를': 1}

In [0]:
int_to_char = dict((i, c) for i, c in enumerate(word_list))
int_to_char

{0: '공부를', 1: '축구를', 2: '싫어한다', 3: '중현은', 4: '도서관을', 5: '좋아한다', 6: '창욱은'}

In [0]:
integer_encoded = []
for token_sentence in token_sentences:
  integer_encoded.append([char_to_int[char] for char in token_sentence])  
  
print(integer_encoded)

[[6, 1, 5], [3, 1, 2], [6, 4, 5], [3, 4, 2], [6, 0, 5], [3, 0, 2], [6, 1, 5, 3, 1, 2], [6, 4, 5, 3, 4, 2], [6, 0, 5, 3, 0, 2]]


### keras Preprocessing API 사용

In [0]:
from tensorflow.keras import preprocessing
# 전시간에 배운 preprocessing의 Tokenizer 함수를 이용하여 Instance를 만든다.
# fit_on_texts 함수에 Token하고자 하는 copus 를 넣는다.
# 문장을 index 처리 한다.

word_index = tokenizer.word_index

In [0]:
print("token_sentences : %s " %sequence)
print("word_list : %s" %word_index)

token_sentences : [[1, 5, 2], [3, 5, 4], [1, 6, 2], [3, 6, 4], [1, 7, 2], [3, 7, 4], [1, 5, 2, 3, 5, 4], [1, 6, 2, 3, 6, 4], [1, 7, 2, 3, 7, 4]] 
word_list : {'창욱은': 1, '좋아한다': 2, '중현은': 3, '싫어한다': 4, '축구를': 5, '도서관을': 6, '공부를': 7}


In [0]:
onehot_encodeds = list()

for values in integer_encoded:
  onehot = list()
  for val in values:
    #모두 0으로 초기화 한다.
    #특정 index에 1로 채워 준다.
    onehot.append(letter)
  onehot_encodeds.append(onehot)

print(onehot_encodeds)

In [0]:
from numpy import argmax
inverted = int_to_char[argmax(onehot_encodeds[0][0])]
print(inverted)

창욱은


### tensorflow onehot endcode 만들기

In [0]:
import tensorflow as tf
onehot_encode = tf.one_hot(indices = integer_encoded[:6], depth = len(int_to_char))

with tf.Session() as sess:
  print(onehot_encode.eval())
  print(onehot_encode)

[[[0. 0. 0. 0. 0. 0. 1.]
  [0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]]

 [[0. 0. 0. 1. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 1.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]]

 [[0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 1.]
  [1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]]

 [[0. 0. 0. 1. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]]]
Tensor("one_hot_43:0", shape=(6, 3, 7), dtype=float32)
