## Attention 구현

### Attention without batch

In [0]:
import numpy as np
import tensorflow as tf

tf.enable_eager_execution()

In [0]:
# 나 는 야구 좋아 
# 나    [0.1, 0.1, 0.1]
# 는    [0.2, 0.2, 0.2]
# 야구  [0.3, 0.3, 0.3]
# 좋아  [0.5, 0.5, 0.5]

L, H = 4, 3 # Length , Hidden

In [3]:
emb = np.array([[0.1, 0.1, 0.1],
               [0.2, 0.2, 0.2],
               [0.3, 0.3, 0.3],
               [0.5, 0.5, 0.5]])
print(emb.shape)

(4, 3)


In [4]:
a = np.random.randn(L,1)
print(a)

[[-0.87619072]
 [-0.30228757]
 [ 1.379005  ]
 [-2.58818915]]


In [5]:
ar = a.repeat(H, axis=1)
print(ar)

[[-0.87619072 -0.87619072 -0.87619072]
 [-0.30228757 -0.30228757 -0.30228757]
 [ 1.379005    1.379005    1.379005  ]
 [-2.58818915 -2.58818915 -2.58818915]]


In [6]:
t = emb * ar
print(t)

[[-0.08761907 -0.08761907 -0.08761907]
 [-0.06045751 -0.06045751 -0.06045751]
 [ 0.4137015   0.4137015   0.4137015 ]
 [-1.29409457 -1.29409457 -1.29409457]]


In [7]:
c = np.sum(t, axis=1)
print(c)

[-0.26285722 -0.18137254  1.2411045  -3.88228372]


### Attention with batch

In [0]:
# 나 는 축구 좋아 
# 나    [0.1, 0.1, 0.1]
# 는    [0.2, 0.2, 0.2]
# 야구  [0.3, 0.3, 0.3]
# 좋아  [0.5, 0.5, 0.5]

# 나 는 야구 좋아 
# 나    [0.1, 0.1, 0.1]
# 는    [0.2, 0.2, 0.2]
# 야구  [0.4, 0.4, 0.4]
# 좋아  [0.5, 0.5, 0.5]
B, L, H = 2, 4, 3

In [9]:
emb = np.array([[[0.1, 0.1, 0.1],
               [0.2, 0.2, 0.2],
               [0.3, 0.3, 0.3],
               [0.5, 0.5, 0.5]],
               [[0.1, 0.1, 0.1],
               [0.2, 0.2, 0.2],
               [0.4, 0.4, 0.4],
               [0.5, 0.5, 0.5]]] )
print(emb.shape)

(2, 4, 3)


In [10]:
a = np.random.randn(B, L, 1)
print(a)

[[[ 0.30310133]
  [ 0.48254973]
  [ 0.09393823]
  [-1.33226639]]

 [[-0.18531422]
  [-0.0709045 ]
  [ 1.27693149]
  [ 0.4375584 ]]]


In [11]:
ar = a.repeat(H, axis=2)
print(ar)

[[[ 0.30310133  0.30310133  0.30310133]
  [ 0.48254973  0.48254973  0.48254973]
  [ 0.09393823  0.09393823  0.09393823]
  [-1.33226639 -1.33226639 -1.33226639]]

 [[-0.18531422 -0.18531422 -0.18531422]
  [-0.0709045  -0.0709045  -0.0709045 ]
  [ 1.27693149  1.27693149  1.27693149]
  [ 0.4375584   0.4375584   0.4375584 ]]]


In [12]:
t = emb * ar
print(t)

[[[ 0.03031013  0.03031013  0.03031013]
  [ 0.09650995  0.09650995  0.09650995]
  [ 0.02818147  0.02818147  0.02818147]
  [-0.66613319 -0.66613319 -0.66613319]]

 [[-0.01853142 -0.01853142 -0.01853142]
  [-0.0141809  -0.0141809  -0.0141809 ]
  [ 0.5107726   0.5107726   0.5107726 ]
  [ 0.2187792   0.2187792   0.2187792 ]]]


In [13]:
c = np.sum(t, axis=2)
print(c)

[[ 0.0909304   0.28952984  0.08454441 -1.99839958]
 [-0.05559427 -0.0425427   1.53231779  0.65633761]]


### Sotfmax

In [14]:
logit = tf.nn.softmax(c, axis=1)
print(logit.numpy())

[[0.29966159 0.36549524 0.29775405 0.03708913]
 [0.11179952 0.11326824 0.54709327 0.22783897]]
