## Attention 구현

### Attention without batch

In [0]:
import numpy as np
import tensorflow as tf

tf.enable_eager_execution()

In [0]:
# 나 는 야구 좋아 
# 나    [0.1, 0.1, 0.1]
# 는    [0.2, 0.2, 0.2]
# 야구  [0.3, 0.3, 0.3]
# 좋아  [0.5, 0.5, 0.5]

L, H = 4, 3 # Length , Hidden

In [3]:
emb = np.array([[0.1, 0.1, 0.1],
               [0.2, 0.2, 0.2],
               [0.3, 0.3, 0.3],
               [0.5, 0.5, 0.5]])
print(emb.shape)

(4, 3)


In [4]:
a = np.random.randn(L,1)
print(a)

[[ 1.40291572]
 [ 0.95090514]
 [-0.07931901]
 [-0.97258694]]


In [5]:
ar = a.repeat(H, axis=1)
print(ar)

[[ 1.40291572  1.40291572  1.40291572]
 [ 0.95090514  0.95090514  0.95090514]
 [-0.07931901 -0.07931901 -0.07931901]
 [-0.97258694 -0.97258694 -0.97258694]]


In [6]:
t = emb * ar
print(t)

[[ 0.14029157  0.14029157  0.14029157]
 [ 0.19018103  0.19018103  0.19018103]
 [-0.0237957  -0.0237957  -0.0237957 ]
 [-0.48629347 -0.48629347 -0.48629347]]


In [7]:
c = np.sum(t, axis=0)
print(c)

[-0.17961657 -0.17961657 -0.17961657]


### Attention with batch

In [0]:
# 나 는 축구 좋아 
# 나    [0.1, 0.1, 0.1]
# 는    [0.2, 0.2, 0.2]
# 야구  [0.3, 0.3, 0.3]
# 좋아  [0.5, 0.5, 0.5]

# 나 는 야구 좋아 
# 나    [0.1, 0.1, 0.1]
# 는    [0.2, 0.2, 0.2]
# 야구  [0.4, 0.4, 0.4]
# 좋아  [0.5, 0.5, 0.5]
B, L, H = 2, 4, 3

In [9]:
emb = np.array([[[0.1, 0.1, 0.1],
               [0.2, 0.2, 0.2],
               [0.3, 0.3, 0.3],
               [0.5, 0.5, 0.5]],
               [[0.1, 0.1, 0.1],
               [0.2, 0.2, 0.2],
               [0.4, 0.4, 0.4],
               [0.5, 0.5, 0.5]]] )
print(emb.shape)

(2, 4, 3)


In [10]:
a = np.random.randn(B, L, 1)
print(a)

[[[-0.97517716]
  [ 0.5057836 ]
  [-0.13420105]
  [-0.58512825]]

 [[-0.28416669]
  [-0.54926265]
  [-0.28580484]
  [-0.2243613 ]]]


In [11]:
ar = a.repeat(H, axis=2)
print(ar)

[[[-0.97517716 -0.97517716 -0.97517716]
  [ 0.5057836   0.5057836   0.5057836 ]
  [-0.13420105 -0.13420105 -0.13420105]
  [-0.58512825 -0.58512825 -0.58512825]]

 [[-0.28416669 -0.28416669 -0.28416669]
  [-0.54926265 -0.54926265 -0.54926265]
  [-0.28580484 -0.28580484 -0.28580484]
  [-0.2243613  -0.2243613  -0.2243613 ]]]


In [12]:
t = emb * ar
print(t)

[[[-0.09751772 -0.09751772 -0.09751772]
  [ 0.10115672  0.10115672  0.10115672]
  [-0.04026032 -0.04026032 -0.04026032]
  [-0.29256412 -0.29256412 -0.29256412]]

 [[-0.02841667 -0.02841667 -0.02841667]
  [-0.10985253 -0.10985253 -0.10985253]
  [-0.11432194 -0.11432194 -0.11432194]
  [-0.11218065 -0.11218065 -0.11218065]]]


In [13]:
c = np.sum(t, axis=1)
print(c)

[[-0.32918544 -0.32918544 -0.32918544]
 [-0.36477179 -0.36477179 -0.36477179]]


### Sotfmax

In [16]:
logit = tf.nn.softmax(c, axis=1)
print(logit.numpy())

[[0.33333333 0.33333333 0.33333333]
 [0.33333333 0.33333333 0.33333333]]
